# Site settings
title: UrbanLabs LLC
tagline: "People. Places. Planet."
email: easall@gmail.com
url: http://urbanlabs.io
description:  "People. Places. Planet."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 00a855
  secondary: 2c3e50
  light: 507292

# Footer settings
footer:
  copyright: UrbanLabs LLC
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/urbanlabsllc
  - title: github
    url: https://github.com/urbanlabs
  - title: linkedin
    url: https://www.linkedin.com/company/urbanlabs-llc/

include: ["team"]

# Postal address (add as many lines as necessary)
address:
  - line: Seattle | Washington | USA

# Credits content
credits: 'Very loosely based on <a href="http://startbootstrap.com">Freelance Bootstrap Theme</a>'

# Build settings
markdown: kramdown
permalink: pretty
